name: amplitude_flutter
description: Official Flutter plugin for tracking events and revenue to Amplitude.
version: 1.1.0
author: Amplitude <platform@amplitude.com>
homepage: https://github.com/amplitude/Amplitude-Flutter

environment:
  sdk: ">=2.7.0-dev.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.1+1
  package_info: ^0.4.0+10
  http: ^0.12.0+2
  crypto: ^2.1.3
  sqflite: ^1.1.7+3
  uuid: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  plugin:
    androidPackage: com.amplitude.amplitude_flutter
    pluginClass: AmplitudeFlutterPlugin
